### ISSUE TITLE
No module named ‘mistune’

### ISSUE THREAD

**Issue by Galaxy955** [Galaxy955/Gemini_Pro_macOS#2]
Gemini_Pro_macOS-master % python main.py
Traceback (most recent call last):
  File "/Gemini_Pro_macOS-master/main.py", line 5, in <module>
    from main_window import Main_Window
  File "/Gemini_Pro_macOS-master/main_window.py", line 5, in <module>
    import mistune
ModuleNotFoundError: No module named 'mistune'

_Originally posted by @Brother-Bob in https://github.com/Galaxy955/Gemini_Pro_macOS/issues/1#issuecomment-1864710535_

**Comment by Galaxy955** [comment]
Gemini Pro will return the responses in the form of Markdown. Mistune package will convert the form of the responses from Markdown to HTML to display in the application. So you should install mistune before running this application. Use “pip install mistune” to install this package.
